//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MileageTokenService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  [
                  {
                  ""Name"": ""Contoso Airline"",
                  ""ContractAddress"": """",
                  ""Address"": ""0x0071df3755926F5C38b4cb68d550807db74DcbAc"",
                  ""TokenAddress"": """"
                  }
                  ,
                  {
                  ""Name"": ""Contoso Rent a Car"",
                  ""ContractAddress"": """",
                  ""Address"": ""0xB897f342D673fB16C38D8Ca4e31F39EE727720A1"",
                  ""TokenAddress"": """"
                  }

                  ]")]
        public string CompanyInfo {
            get {
                return ((string)(this["CompanyInfo"]));
            }
            set {
                this["CompanyInfo"] = value;
            }
        }
    }
}
