//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeToken.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""TokenName"":""Airline Token"",""TokenSymbol"":null,""TotalAmountToken"":0.0,""TokenContractAddress"":""0xb2da78d1f8ebf31b824ff2df10ece8ead00e84b7""},{""TokenName"":""Car Token"",""TokenSymbol"":null,""TotalAmountToken"":0.0,""TokenContractAddress"":""0x88bf7a8fce51bba89eed6eeaaf4b9b6f71888259""}]")]
        public string TokenInfos {
            get {
                return ((string)(this["TokenInfos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""AccountName"":""Application (Consortium Admin)"",""AccountPubAddress"":""0xFF1D19EBE9Da2D81Ce5480a2Dab1C1C5faA3e2dD""},{""AccountName"":""Consoto Airline"",""AccountPubAddress"":""0x0071df3755926F5C38b4cb68d550807db74DcbAc""},{""AccountName"":""Contoso Rent a car"",""AccountPubAddress"":""0xB897f342D673fB16C38D8Ca4e31F39EE727720A1""},{""AccountName"":""Bob"",""AccountPubAddress"":""0x1F9B9484188b42C01f4aaC308D4848659901F17b""},{""AccountName"":""Mary"",""AccountPubAddress"":""0x0f5DDacC06A44163badc5eD4f09dE0d3eFfC2716""},{""AccountName"":""Jason"",""AccountPubAddress"":""0xC3c76b85b44840CD8E03C01c09cC85522108faAE""},{""AccountName"":""DB"",""AccountPubAddress"":""0xdDE43471B86d4e001a0ad122CbF8b1F3011f17b3""}]")]
        public string UserInfos {
            get {
                return ((string)(this["UserInfos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x4f339295ec73c65d1e8cf9f384d6a697637ce1d2")]
        public string ExchangeTokenContractAddress {
            get {
                return ((string)(this["ExchangeTokenContractAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ready20loyalty.azurefd.net")]
        public string APILocation {
            get {
                return ((string)(this["APILocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0xFF1D19EBE9Da2D81Ce5480a2Dab1C1C5faA3e2dD")]
        public string ApplicationAddress {
            get {
                return ((string)(this["ApplicationAddress"]));
            }
        }
    }
}
