FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
#COPY ./ ./
COPY /TR20.Loyalty.LedgerClient/ .
COPY /TR20.Loyalty.ServiceProxy /TR20.Loyalty.ServiceProxy/
COPY /TR20.Loyalty.OffChainRepository.Mongo /TR20.Loyalty.OffChainRepository.Mongo/
RUN dotnet restore

# Copy everything else and build
COPY /TR20.Loyalty.LedgerClient/ .
COPY /TR20.Loyalty.ServiceProxy/ .

WORKDIR /app/LedgerClient.Host/
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/LedgerClient.Host/out ./
ENTRYPOINT ["dotnet", "LedgerClient.Host.dll"]