FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY /TR20.Loyalty.TxIndexer/ .
COPY /TR20.Loyalty.OffChainRepository.Mongo /TR20.Loyalty.OffChainRepository.Mongo/
COPY /TR20.Loyalty.ServiceProxy /TR20.Loyalty.ServiceProxy/
WORKDIR /app/TxIndexer.Host/
RUN dotnet restore

# Copy everything else and build
WORKDIR /app
COPY /TR20.Loyalty.TxIndexer/ .
COPY /TR20.Loyalty.OffChainRepository.Mongo /TR20.Loyalty.OffChainRepository.Mongo/

WORKDIR /app/TxIndexer.Host/
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/TxIndexer.Host/out ./
ENTRYPOINT ["dotnet", "TxIndexer.Host.dll"]