FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY /TR20.Loyalty.TxTracker/ .
COPY /TR20.Loyalty.OffChainRepository.Mongo /TR20.Loyalty.OffChainRepository.Mongo/

WORKDIR /app/TxTracker.Host/
RUN dotnet restore

# Copy everything else and build
WORKDIR /app
COPY /TR20.Loyalty.TxTracker/ .
COPY /TR20.Loyalty.OffChainRepository.Mongo /TR20.Loyalty.OffChainRepository.Mongo/

WORKDIR /app/TxTracker.Host/
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/TxTracker.Host/out ./
ENTRYPOINT ["dotnet", "TxTracker.Host.dll"]